using System.Collections.Generic;
using System.ComponentModel;

namespace Core_Aim.Services
{
    public class LocalizationManager : INotifyPropertyChanged
    {
        public static readonly LocalizationManager Instance = new();

        public event PropertyChangedEventHandler? PropertyChanged;

        private readonly Dictionary<string, string> _pt = new()
        {
            // ── Panel headers ──────────────────────────────────────────
            ["Hardware"]    = "HARDWARE",
            ["DetMode"]     = "MODO DE DETECÇÃO",
            ["TrackCtrl"]   = "TRACKING CONTROL",
            ["Trigger"]     = "GATILHO & DISPARO",
            ["Offset"]      = "TARGET OFFSET",
            ["Recoil"]      = "ANTI-RECOIL",
            ["PixelBot"]    = "PIXELBOT (COR)",
            ["Overlay"]     = "OVERLAY",
            ["Vision"]      = "VISÃO & IA",
            ["Save"]        = "SALVAR IMAGENS",
            ["Capture"]     = "CAPTURA",
            ["Monitor"]     = "MONITOR",

            // ── Panel 1 — Hardware ─────────────────────────────────────
            ["Protocol"]        = "Protocolo",
            ["Slot"]            = "Slot",
            ["IpAddress"]       = "Endereço IP",
            ["Port"]            = "Porta",
            ["UUID"]            = "UUID",
            ["GpuInference"]    = "GPU para Inferência",
            ["Gpu0"]            = "GPU 0 (principal)",
            ["Gpu1"]            = "GPU 1",
            ["Gpu2"]            = "GPU 2",
            ["PanelKey"]        = "Tecla Painéis (+ Ctrl)",

            // ── Panel 2 — Detection Mode ───────────────────────────────
            ["DM0"]     = "0 — Apenas YOLO",
            ["DM1"]     = "1 — YOLO + PB fallback",
            ["DM2"]     = "2 — Apenas PixelBot",
            ["DM3"]     = "3 — PB como gate",

            // ── Panel 3 — Tracking Control ─────────────────────────────
            ["SectYolo"]    = "— YOLO —",
            ["SectPB"]      = "— PixelBot —",
            ["Speed"]       = "Velocidade",
            ["Smoothness"]  = "Suavidade",
            ["DeadZone"]    = "Zona Morta (px)",
            ["SpeedPB100"]  = "Velocidade PB (1–100)",
            ["SmoothPB99"]  = "Suavidade PB (1–99)",
            ["DeadZonePB"]  = "Zona Morta PB (px)",
            ["SpeedHIP"]    = "Velocidade HIP",
            ["SpeedADS"]    = "Velocidade ADS",
            ["Boost"]       = "Multiplicador",
            ["MinForce"]    = "Força Mínima",
            ["Damping"]     = "Amortecimento",
            ["ResponseCurve"] = "Curva de Resposta",
            ["Curve0"]      = "0 — Linear",
            ["Curve1"]      = "1 — Quadrático",
            ["Curve2"]      = "2 — Raiz Quadrada",
            ["Curve3"]      = "3 — Suave / S-Curve",
            ["Curve4"]      = "4 — Exponencial",
            ["Curve5"]      = "5 — Bang + Linear",
            ["Curve6"]      = "6 — Cúbico",
            ["TrackFov"]    = "FOV de Rastreio",
            ["AutoTune"]    = "Auto-Tune",

            // ── Panel 4 — Trigger ──────────────────────────────────────
            ["TriggerLabel"]    = "Gatilho",
            ["InferenceMode"]   = "Modo de Inferência",
            ["IM0"]     = "Auto (inferência só no gatilho)",
            ["IM1"]     = "Constante (rastreio só no gatilho)",
            ["IM2"]     = "Constante (rastreio sempre ativo)",
            ["IM3"]     = "Desligado",

            // ── Panel 5 — Offset ───────────────────────────────────────
            ["BodyOffset"]  = "Body Offset  (0=pé  100=topo)",
            ["IconOffset"]  = "Icon Offset  (0=pé  100=abaixo)",

            // ── Panel 6 — Anti-Recoil ──────────────────────────────────
            ["SectKmBox"]       = "— KMBox —",
            ["SectTitanTwo"]    = "— Titan Two —",
            ["EnableRecoil"]    = "Ativar Anti-Recoil",
            ["RecoilVert"]      = "Vertical (px/pulso)",
            ["RecoilHoriz"]     = "Horizontal (px/pulso)",
            ["Interval"]        = "Intervalo (ms)",
            ["RecoilVertTT2"]   = "Vertical (% stick contínuo)",
            ["RecoilHorizTT2"]  = "Horizontal (% stick contínuo)",

            // ── Panel 7 — PixelBot ─────────────────────────────────────
            ["ResetDefaults"]       = "↺  Resetar para valores padrão",
            ["TargetColor"]         = "Cor Alvo",
            ["MinArea"]             = "Área Mínima (px²)",
            ["MaxArea"]             = "Área Máxima (px²)",
            ["MinAspect"]           = "Aspect Ratio Mín.",
            ["MinSolidity"]         = "Solidez Mín. (0=off)",
            ["MinCircularity"]      = "Circularidade Mín. (0=off)",
            ["SatMin"]              = "Saturação Mín. HSV",
            ["ValMin"]              = "Brilho Mín. HSV",
            ["PersistRadius"]       = "Raio Persistência (px)",
            ["PersistFrames"]       = "Frames Persistência",
            ["PbVertOffset"]        = "Offset Vertical PB  (0=pé  100=topo)",

            // ── Panel 8 — Overlay ──────────────────────────────────────
            ["Metrics"]         = "MÉTRICAS",
            ["ShowMetrics"]     = "Mostrar barra de métricas",
            ["DragMetrics"]     = "Arraste a barra para reposicionar",
            ["FovSection"]      = "FOV",
            ["ShowFov"]         = "Mostrar FOV",
            ["FovSize"]         = "Tamanho FOV (px)",
            ["FovThickness"]    = "Espessura FOV",
            ["FovStyle"]        = "Estilo FOV",
            ["FovColor"]        = "Cor FOV",
            ["Circle"]          = "Círculo",
            ["Square"]          = "Quadrado",
            ["BoxSection"]      = "CAIXAS",
            ["ShowBox"]         = "Mostrar Caixas",
            ["BoxStyle"]        = "Estilo da Caixa",
            ["BoxThickness"]    = "Espessura",
            ["BoxFill"]         = "Preenchimento",
            ["BoxAlpha"]        = "Opacidade Fill",
            ["BoxStyleFull"]    = "Quadrado",
            ["BoxStyleCorners"] = "Apenas Cantos",
            ["BoxStyleRound"]   = "Arredondado",

            // ── Panel 9 — Vision & AI ──────────────────────────────────
            ["Model"]           = "Modelo",
            ["Confidence"]      = "Confiança Mínima",
            ["ColorFilter"]     = "Color Filter",
            ["ColorTolerance"]  = "Tolerância de Cor",
            ["PreviewLbl"]      = "Preview",
            ["PreviewFpsLbl"]   = "FPS Preview",

            // ── Panel 10 — Save ────────────────────────────────────────
            ["AutoSaveLbl"]     = "Auto-Save",
            ["SaveEnemyOnly"]   = "Salvar apenas Enemy",
            ["CropSize"]        = "Tamanho do Crop",

            // ── Control bar ────────────────────────────────────────────
            ["Language"]        = "Idioma",

            // ── UI extras (new) ───────────────────────────────────────
            ["NoSignal"]            = "SEM SINAL",
            ["PressStart"]          = "Pressione START para iniciar",
            ["OutputLog"]           = "LOG DE SAÍDA",
            ["VideoCaptureDevice"]  = "Dispositivo de Captura de Vídeo",
            ["VideoInputConfig"]    = "Configuração de Entrada de Vídeo",
            ["FrameResolution"]     = "Resolução do Frame",
            ["AdvancedConfig"]      = "Avançado (chave=valor)",
            ["DetectDevices"]       = "Detectar",
            ["ScreenCaptureInfo"]   = "Captura de tela ativa — recorte central enviado à inferência.",
            ["MacrosTitan"]         = "Macros Titan (CoD)",
            ["StickOverride"]       = "Override do Stick",
            ["MacroAdjustments"]    = "Ajustes de Macro",
            ["PlayerBlendLbl"]      = "Player Blend (IA ativa)",
            ["DisableAiThreshold"]  = "Threshold p/ Desligar IA (%)",
            ["ArVertical"]          = "Anti-Recoil Vertical",
            ["ArHorizontal"]        = "Anti-Recoil Horizontal",
            ["RapidFireSpeed"]      = "Velocidade Rapid Fire (ms)",
            ["QuickscopeDelay"]     = "Atraso Quickscope (ms)",
            ["JumpShotDelay"]       = "Atraso Jump Shot (ms)",
            ["BunnyHopDelay"]       = "Atraso Bunny Hop (ms)",
            ["StrafePower"]         = "Força Strafe",
            // ── User Panel ────────────────────────────────────────────
            ["UserPanel"]           = "PAINEL DO USUÁRIO",
            ["AccountInfo"]         = "Informações da Conta",
            ["AccUsername"]         = "Usuário",
            ["AccSubscription"]     = "Assinatura",
            ["AccExpiry"]           = "Expiração",
            ["AccCreated"]          = "Criado em",
            ["AccLastLogin"]        = "Último Login",
            ["ConfigProfiles"]      = "Perfis de Configuração",
            ["ActiveProfileLbl"]    = "Perfil Ativo:",
            ["NoProfilesMsg"]       = "Nenhum perfil encontrado — crie um novo para começar.",
            ["NewProfilePlaceholder"] = "Nome do novo perfil",
            ["BtnCreate"]           = "CRIAR",
            ["BtnLoad"]             = "CARREGAR",
            ["BtnSave"]             = "SALVAR",
            ["BtnCopy"]             = "COPIAR",
            ["BtnPaste"]            = "COLAR",
            ["BtnDelete"]           = "EXCLUIR",
            ["FuzerMode"]           = "Modo Fuzer",
            ["FuzerExit"]           = "Sair do Fuzer",
        };

        private readonly Dictionary<string, string> _en = new()
        {
            ["Hardware"]    = "HARDWARE",
            ["DetMode"]     = "DETECTION MODE",
            ["TrackCtrl"]   = "TRACKING CONTROL",
            ["Trigger"]     = "TRIGGER & FIRE",
            ["Offset"]      = "TARGET OFFSET",
            ["Recoil"]      = "ANTI-RECOIL",
            ["PixelBot"]    = "PIXELBOT (COLOR)",
            ["Overlay"]     = "OVERLAY",
            ["Vision"]      = "VISION & AI",
            ["Save"]        = "SAVE IMAGES",
            ["Capture"]     = "CAPTURE",
            ["Monitor"]     = "MONITOR",

            ["Protocol"]        = "Protocol",
            ["Slot"]            = "Slot",
            ["IpAddress"]       = "IP Address",
            ["Port"]            = "Port",
            ["UUID"]            = "UUID",
            ["GpuInference"]    = "GPU for Inference",
            ["Gpu0"]            = "GPU 0 (main)",
            ["Gpu1"]            = "GPU 1",
            ["Gpu2"]            = "GPU 2",
            ["PanelKey"]        = "Panel Key (+ Ctrl)",

            ["DM0"]     = "0 — YOLO Only",
            ["DM1"]     = "1 — YOLO + PB fallback",
            ["DM2"]     = "2 — PixelBot Only",
            ["DM3"]     = "3 — PB as gate",

            ["SectYolo"]    = "— YOLO —",
            ["SectPB"]      = "— PixelBot —",
            ["Speed"]       = "Speed",
            ["Smoothness"]  = "Smoothness",
            ["DeadZone"]    = "Dead Zone (px)",
            ["SpeedPB100"]  = "PB Speed (1–100)",
            ["SmoothPB99"]  = "PB Smoothness (1–99)",
            ["DeadZonePB"]  = "PB Dead Zone (px)",
            ["SpeedHIP"]    = "HIP Speed",
            ["SpeedADS"]    = "ADS Speed",
            ["Boost"]       = "Boost",
            ["MinForce"]    = "Min Force",
            ["Damping"]     = "Damping",
            ["ResponseCurve"] = "Response Curve",
            ["Curve0"]      = "0 — Linear",
            ["Curve1"]      = "1 — Quadratic",
            ["Curve2"]      = "2 — Square Root",
            ["Curve3"]      = "3 — Smooth / S-Curve",
            ["Curve4"]      = "4 — Exponential",
            ["Curve5"]      = "5 — Bang + Linear",
            ["Curve6"]      = "6 — Cubic",
            ["TrackFov"]    = "Tracking FOV",
            ["AutoTune"]    = "Auto-Tune",

            ["TriggerLabel"]    = "Trigger",
            ["InferenceMode"]   = "Inference Mode",
            ["IM0"]     = "Auto (infer on trigger only)",
            ["IM1"]     = "Constant (track on trigger)",
            ["IM2"]     = "Constant (always tracking)",
            ["IM3"]     = "Off",

            ["BodyOffset"]  = "Body Offset  (0=feet  100=top)",
            ["IconOffset"]  = "Icon Offset  (0=feet  100=below)",

            ["SectKmBox"]       = "— KMBox —",
            ["SectTitanTwo"]    = "— Titan Two —",
            ["EnableRecoil"]    = "Enable Anti-Recoil",
            ["RecoilVert"]      = "Vertical (px/pulse)",
            ["RecoilHoriz"]     = "Horizontal (px/pulse)",
            ["Interval"]        = "Interval (ms)",
            ["RecoilVertTT2"]   = "Vertical (% continuous stick)",
            ["RecoilHorizTT2"]  = "Horizontal (% continuous stick)",

            ["ResetDefaults"]       = "↺  Reset to defaults",
            ["TargetColor"]         = "Target Color",
            ["MinArea"]             = "Min Area (px²)",
            ["MaxArea"]             = "Max Area (px²)",
            ["MinAspect"]           = "Min Aspect Ratio",
            ["MinSolidity"]         = "Min Solidity (0=off)",
            ["MinCircularity"]      = "Min Circularity (0=off)",
            ["SatMin"]              = "Min HSV Saturation",
            ["ValMin"]              = "Min HSV Brightness",
            ["PersistRadius"]       = "Persist Radius (px)",
            ["PersistFrames"]       = "Persist Frames",
            ["PbVertOffset"]        = "PB Vertical Offset  (0=feet  100=top)",

            ["Metrics"]         = "METRICS",
            ["ShowMetrics"]     = "Show metrics bar",
            ["DragMetrics"]     = "Drag the bar to reposition",
            ["FovSection"]      = "FOV",
            ["ShowFov"]         = "Show FOV",
            ["FovSize"]         = "FOV Size (px)",
            ["FovThickness"]    = "FOV Thickness",
            ["FovStyle"]        = "FOV Style",
            ["FovColor"]        = "FOV Color",
            ["Circle"]          = "Circle",
            ["Square"]          = "Square",
            ["BoxSection"]      = "BOUNDING BOXES",
            ["ShowBox"]         = "Show Boxes",
            ["BoxStyle"]        = "Box Style",
            ["BoxThickness"]    = "Thickness",
            ["BoxFill"]         = "Fill",
            ["BoxAlpha"]        = "Fill Opacity",
            ["BoxStyleFull"]    = "Square",
            ["BoxStyleCorners"] = "Corners Only",
            ["BoxStyleRound"]   = "Rounded",

            ["Model"]           = "Model",
            ["Confidence"]      = "Min. Confidence",
            ["ColorFilter"]     = "Color Filter",
            ["ColorTolerance"]  = "Color Tolerance",
            ["PreviewLbl"]      = "Preview",
            ["PreviewFpsLbl"]   = "Preview FPS",

            ["AutoSaveLbl"]     = "Auto-Save",
            ["SaveEnemyOnly"]   = "Save Enemy Only",
            ["CropSize"]        = "Crop Size",

            ["Language"]        = "Language",

            ["NoSignal"]            = "NO SIGNAL",
            ["PressStart"]          = "Press START to begin",
            ["OutputLog"]           = "OUTPUT LOG",
            ["VideoCaptureDevice"]  = "Video Capture Device",
            ["VideoInputConfig"]    = "Video Input Configuration",
            ["FrameResolution"]     = "Frame Resolution",
            ["AdvancedConfig"]      = "Advanced (key=value)",
            ["DetectDevices"]       = "Detect",
            ["ScreenCaptureInfo"]   = "Full desktop capture active — center crop sent to inference.",
            ["MacrosTitan"]         = "Macros Titan (CoD)",
            ["StickOverride"]       = "Stick Override",
            ["MacroAdjustments"]    = "Macro Adjustments",
            ["PlayerBlendLbl"]      = "Player Blend (AI active)",
            ["DisableAiThreshold"]  = "Disable AI Threshold (%)",
            ["ArVertical"]          = "Anti-Recoil Vertical",
            ["ArHorizontal"]        = "Anti-Recoil Horizontal",
            ["RapidFireSpeed"]      = "Rapid Fire Speed (ms)",
            ["QuickscopeDelay"]     = "Quickscope Delay (ms)",
            ["JumpShotDelay"]       = "Jump Shot Delay (ms)",
            ["BunnyHopDelay"]       = "Bunny Hop Delay (ms)",
            ["StrafePower"]         = "Strafe Power",
            // ── User Panel ────────────────────────────────────────────
            ["UserPanel"]           = "USER PANEL",
            ["AccountInfo"]         = "Account Information",
            ["AccUsername"]         = "Username",
            ["AccSubscription"]     = "Subscription",
            ["AccExpiry"]           = "Expiry",
            ["AccCreated"]          = "Created",
            ["AccLastLogin"]        = "Last Login",
            ["ConfigProfiles"]      = "Config Profiles",
            ["ActiveProfileLbl"]    = "Active Profile:",
            ["NoProfilesMsg"]       = "No profiles found — create a new one to get started.",
            ["NewProfilePlaceholder"] = "New profile name",
            ["BtnCreate"]           = "CREATE",
            ["BtnLoad"]             = "LOAD",
            ["BtnSave"]             = "SAVE",
            ["BtnCopy"]             = "COPY",
            ["BtnPaste"]            = "PASTE",
            ["BtnDelete"]           = "DELETE",
            ["FuzerMode"]           = "Fuzer Mode",
            ["FuzerExit"]           = "Exit Fuzer",
        };

        private readonly Dictionary<string, string> _fr = new()
        {
            ["Hardware"]    = "MATÉRIEL",
            ["DetMode"]     = "MODE DÉTECTION",
            ["TrackCtrl"]   = "CONTRÔLE SUIVI",
            ["Trigger"]     = "GÂCHETTE",
            ["Offset"]      = "DÉCALAGE CIBLE",
            ["Recoil"]      = "ANTI-RECUL",
            ["PixelBot"]    = "PIXELBOT (COULEUR)",
            ["Overlay"]     = "OVERLAY",
            ["Vision"]      = "VISION & IA",
            ["Save"]        = "SAUVEGARDER",
            ["Capture"]     = "CAPTURE",
            ["Monitor"]     = "MONITEUR",

            ["Protocol"]        = "Protocole",
            ["Slot"]            = "Slot",
            ["IpAddress"]       = "Adresse IP",
            ["Port"]            = "Port",
            ["UUID"]            = "UUID",
            ["GpuInference"]    = "GPU pour l'inférence",
            ["Gpu0"]            = "GPU 0 (principal)",
            ["Gpu1"]            = "GPU 1",
            ["Gpu2"]            = "GPU 2",
            ["PanelKey"]        = "Touche Panneau (+ Ctrl)",

            ["DM0"]     = "0 — YOLO Seulement",
            ["DM1"]     = "1 — YOLO + PB fallback",
            ["DM2"]     = "2 — PixelBot Seulement",
            ["DM3"]     = "3 — PB comme filtre",

            ["SectYolo"]    = "— YOLO —",
            ["SectPB"]      = "— PixelBot —",
            ["Speed"]       = "Vitesse",
            ["Smoothness"]  = "Douceur",
            ["DeadZone"]    = "Zone morte (px)",
            ["SpeedPB100"]  = "Vitesse PB (1–100)",
            ["SmoothPB99"]  = "Douceur PB (1–99)",
            ["DeadZonePB"]  = "Zone morte PB (px)",
            ["SpeedHIP"]    = "Vitesse HIP",
            ["SpeedADS"]    = "Vitesse ADS",
            ["Boost"]       = "Multiplicateur",
            ["MinForce"]    = "Force min.",
            ["Damping"]     = "Amortissement",
            ["ResponseCurve"] = "Courbe de réponse",
            ["Curve0"]      = "0 — Linéaire",
            ["Curve1"]      = "1 — Quadratique",
            ["Curve2"]      = "2 — Racine carrée",
            ["Curve3"]      = "3 — Lisse / S-Curve",
            ["Curve4"]      = "4 — Exponentielle",
            ["Curve5"]      = "5 — Bang + Linéaire",
            ["Curve6"]      = "6 — Cubique",
            ["TrackFov"]    = "FOV de suivi",
            ["AutoTune"]    = "Auto-Tune",

            ["TriggerLabel"]    = "Gâchette",
            ["InferenceMode"]   = "Mode d'inférence",
            ["IM0"]     = "Auto (inférence sur gâchette)",
            ["IM1"]     = "Constant (suivi sur gâchette)",
            ["IM2"]     = "Constant (toujours actif)",
            ["IM3"]     = "Désactivé",

            ["BodyOffset"]  = "Décalage corps  (0=pieds  100=tête)",
            ["IconOffset"]  = "Décalage icône  (0=pieds  100=bas)",

            ["SectKmBox"]       = "— KMBox —",
            ["SectTitanTwo"]    = "— Titan Two —",
            ["EnableRecoil"]    = "Activer Anti-Recul",
            ["RecoilVert"]      = "Vertical (px/impulsion)",
            ["RecoilHoriz"]     = "Horizontal (px/impulsion)",
            ["Interval"]        = "Intervalle (ms)",
            ["RecoilVertTT2"]   = "Vertical (% stick continu)",
            ["RecoilHorizTT2"]  = "Horizontal (% stick continu)",

            ["ResetDefaults"]       = "↺  Réinitialiser les valeurs",
            ["TargetColor"]         = "Couleur cible",
            ["MinArea"]             = "Aire min. (px²)",
            ["MaxArea"]             = "Aire max. (px²)",
            ["MinAspect"]           = "Ratio min.",
            ["MinSolidity"]         = "Solidité min. (0=off)",
            ["MinCircularity"]      = "Circularité min. (0=off)",
            ["SatMin"]              = "Saturation HSV min.",
            ["ValMin"]              = "Luminosité HSV min.",
            ["PersistRadius"]       = "Rayon persistance (px)",
            ["PersistFrames"]       = "Frames persistance",
            ["PbVertOffset"]        = "Décalage vertical PB  (0=pieds  100=tête)",

            ["Metrics"]         = "MÉTRIQUES",
            ["ShowMetrics"]     = "Afficher la barre de métriques",
            ["DragMetrics"]     = "Glisser la barre pour déplacer",
            ["FovSection"]      = "FOV",
            ["ShowFov"]         = "Afficher FOV",
            ["FovSize"]         = "Taille FOV (px)",
            ["FovThickness"]    = "Épaisseur FOV",
            ["FovStyle"]        = "Style FOV",
            ["FovColor"]        = "Couleur FOV",
            ["Circle"]          = "Cercle",
            ["Square"]          = "Carré",
            ["BoxSection"]      = "BOÎTES",
            ["ShowBox"]         = "Afficher les boîtes",
            ["BoxStyle"]        = "Style de boîte",
            ["BoxThickness"]    = "Épaisseur",
            ["BoxFill"]         = "Remplissage",
            ["BoxAlpha"]        = "Opacité fill",
            ["BoxStyleFull"]    = "Carré",
            ["BoxStyleCorners"] = "Coins seulement",
            ["BoxStyleRound"]   = "Arrondi",

            ["Model"]           = "Modèle",
            ["Confidence"]      = "Confiance min.",
            ["ColorFilter"]     = "Filtre couleur",
            ["ColorTolerance"]  = "Tolérance couleur",
            ["PreviewLbl"]      = "Aperçu",
            ["PreviewFpsLbl"]   = "FPS Aperçu",

            ["AutoSaveLbl"]     = "Auto-Save",
            ["SaveEnemyOnly"]   = "Ennemis seulement",
            ["CropSize"]        = "Taille du crop",

            ["Language"]        = "Langue",

            ["NoSignal"]            = "PAS DE SIGNAL",
            ["PressStart"]          = "Appuyez sur START pour commencer",
            ["OutputLog"]           = "JOURNAL DE SORTIE",
            ["VideoCaptureDevice"]  = "Périphérique de capture vidéo",
            ["VideoInputConfig"]    = "Configuration entrée vidéo",
            ["FrameResolution"]     = "Résolution de l'image",
            ["AdvancedConfig"]      = "Avancé (clé=valeur)",
            ["DetectDevices"]       = "Détecter",
            ["ScreenCaptureInfo"]   = "Capture d'écran active — recadrage central envoyé à l'inférence.",
            ["MacrosTitan"]         = "Macros Titan (CoD)",
            ["StickOverride"]       = "Override du stick",
            ["MacroAdjustments"]    = "Réglages macro",
            ["PlayerBlendLbl"]      = "Mélange joueur (IA active)",
            ["DisableAiThreshold"]  = "Seuil désact. IA (%)",
            ["ArVertical"]          = "Anti-Recul Vertical",
            ["ArHorizontal"]        = "Anti-Recul Horizontal",
            ["RapidFireSpeed"]      = "Vitesse Rapid Fire (ms)",
            ["QuickscopeDelay"]     = "Délai Quickscope (ms)",
            ["JumpShotDelay"]       = "Délai Jump Shot (ms)",
            ["BunnyHopDelay"]       = "Délai Bunny Hop (ms)",
            ["StrafePower"]         = "Puissance Strafe",
            ["UserPanel"]           = "PANNEAU UTILISATEUR",
            ["AccountInfo"]         = "Informations du Compte",
            ["AccUsername"]         = "Utilisateur",
            ["AccSubscription"]     = "Abonnement",
            ["AccExpiry"]           = "Expiration",
            ["AccCreated"]          = "Créé le",
            ["AccLastLogin"]        = "Dernière Connexion",
            ["ConfigProfiles"]      = "Profils de Configuration",
            ["ActiveProfileLbl"]    = "Profil Actif :",
            ["NoProfilesMsg"]       = "Aucun profil trouvé — créez-en un pour commencer.",
            ["NewProfilePlaceholder"] = "Nom du nouveau profil",
            ["BtnCreate"]           = "CRÉER",
            ["BtnLoad"]             = "CHARGER",
            ["BtnSave"]             = "SAUVER",
            ["BtnCopy"]             = "COPIER",
            ["BtnPaste"]            = "COLLER",
            ["BtnDelete"]           = "SUPPRIMER",
            ["FuzerMode"]           = "Mode Fuzer",
            ["FuzerExit"]           = "Quitter Fuzer",
        };

        private readonly Dictionary<string, string> _es = new()
        {
            ["Hardware"]    = "HARDWARE",
            ["DetMode"]     = "MODO DETECCIÓN",
            ["TrackCtrl"]   = "CONTROL RASTREO",
            ["Trigger"]     = "GATILLO",
            ["Offset"]      = "OFFSET OBJETIVO",
            ["Recoil"]      = "ANTI-RETROCESO",
            ["PixelBot"]    = "PIXELBOT (COLOR)",
            ["Overlay"]     = "OVERLAY",
            ["Vision"]      = "VISIÓN & IA",
            ["Save"]        = "GUARDAR IMÁGENES",
            ["Capture"]     = "CAPTURA",
            ["Monitor"]     = "MONITOR",

            ["Protocol"]        = "Protocolo",
            ["Slot"]            = "Slot",
            ["IpAddress"]       = "Dirección IP",
            ["Port"]            = "Puerto",
            ["UUID"]            = "UUID",
            ["GpuInference"]    = "GPU para Inferencia",
            ["Gpu0"]            = "GPU 0 (principal)",
            ["Gpu1"]            = "GPU 1",
            ["Gpu2"]            = "GPU 2",
            ["PanelKey"]        = "Tecla Panel (+ Ctrl)",

            ["DM0"]     = "0 — Solo YOLO",
            ["DM1"]     = "1 — YOLO + PB fallback",
            ["DM2"]     = "2 — Solo PixelBot",
            ["DM3"]     = "3 — PB como filtro",

            ["SectYolo"]    = "— YOLO —",
            ["SectPB"]      = "— PixelBot —",
            ["Speed"]       = "Velocidad",
            ["Smoothness"]  = "Suavidad",
            ["DeadZone"]    = "Zona muerta (px)",
            ["SpeedPB100"]  = "Velocidad PB (1–100)",
            ["SmoothPB99"]  = "Suavidad PB (1–99)",
            ["DeadZonePB"]  = "Zona muerta PB (px)",
            ["SpeedHIP"]    = "Velocidad HIP",
            ["SpeedADS"]    = "Velocidad ADS",
            ["Boost"]       = "Multiplicador",
            ["MinForce"]    = "Fuerza mín.",
            ["Damping"]     = "Amortiguación",
            ["ResponseCurve"] = "Curva de respuesta",
            ["Curve0"]      = "0 — Lineal",
            ["Curve1"]      = "1 — Cuadrático",
            ["Curve2"]      = "2 — Raíz cuadrada",
            ["Curve3"]      = "3 — Suave / S-Curve",
            ["Curve4"]      = "4 — Exponencial",
            ["Curve5"]      = "5 — Bang + Lineal",
            ["Curve6"]      = "6 — Cúbico",
            ["TrackFov"]    = "FOV de rastreo",
            ["AutoTune"]    = "Auto-Tune",

            ["TriggerLabel"]    = "Gatillo",
            ["InferenceMode"]   = "Modo de inferencia",
            ["IM0"]     = "Auto (inferencia en gatillo)",
            ["IM1"]     = "Constante (rastreo en gatillo)",
            ["IM2"]     = "Constante (siempre activo)",
            ["IM3"]     = "Apagado",

            ["BodyOffset"]  = "Offset cuerpo  (0=pies  100=cabeza)",
            ["IconOffset"]  = "Offset icono  (0=pies  100=abajo)",

            ["SectKmBox"]       = "— KMBox —",
            ["SectTitanTwo"]    = "— Titan Two —",
            ["EnableRecoil"]    = "Activar Anti-Retroceso",
            ["RecoilVert"]      = "Vertical (px/pulso)",
            ["RecoilHoriz"]     = "Horizontal (px/pulso)",
            ["Interval"]        = "Intervalo (ms)",
            ["RecoilVertTT2"]   = "Vertical (% stick continuo)",
            ["RecoilHorizTT2"]  = "Horizontal (% stick continuo)",

            ["ResetDefaults"]       = "↺  Restaurar valores",
            ["TargetColor"]         = "Color objetivo",
            ["MinArea"]             = "Área mín. (px²)",
            ["MaxArea"]             = "Área máx. (px²)",
            ["MinAspect"]           = "Relación aspecto mín.",
            ["MinSolidity"]         = "Solidez mín. (0=off)",
            ["MinCircularity"]      = "Circularidad mín. (0=off)",
            ["SatMin"]              = "Saturación HSV mín.",
            ["ValMin"]              = "Brillo HSV mín.",
            ["PersistRadius"]       = "Radio persistencia (px)",
            ["PersistFrames"]       = "Frames persistencia",
            ["PbVertOffset"]        = "Offset vertical PB  (0=pies  100=cabeza)",

            ["Metrics"]         = "MÉTRICAS",
            ["ShowMetrics"]     = "Mostrar barra de métricas",
            ["DragMetrics"]     = "Arrastra la barra para reposicionar",
            ["FovSection"]      = "FOV",
            ["ShowFov"]         = "Mostrar FOV",
            ["FovSize"]         = "Tamaño FOV (px)",
            ["FovThickness"]    = "Grosor FOV",
            ["FovStyle"]        = "Estilo FOV",
            ["FovColor"]        = "Color FOV",
            ["Circle"]          = "Círculo",
            ["Square"]          = "Cuadrado",
            ["BoxSection"]      = "CAJAS",
            ["ShowBox"]         = "Mostrar Cajas",
            ["BoxStyle"]        = "Estilo de caja",
            ["BoxThickness"]    = "Grosor",
            ["BoxFill"]         = "Relleno",
            ["BoxAlpha"]        = "Opacidad fill",
            ["BoxStyleFull"]    = "Cuadrado",
            ["BoxStyleCorners"] = "Solo esquinas",
            ["BoxStyleRound"]   = "Redondeado",

            ["Model"]           = "Modelo",
            ["Confidence"]      = "Confianza mín.",
            ["ColorFilter"]     = "Filtro color",
            ["ColorTolerance"]  = "Tolerancia color",
            ["PreviewLbl"]      = "Vista previa",
            ["PreviewFpsLbl"]   = "FPS Vista previa",

            ["AutoSaveLbl"]     = "Auto-Save",
            ["SaveEnemyOnly"]   = "Solo enemigos",
            ["CropSize"]        = "Tamaño crop",

            ["Language"]        = "Idioma",

            ["NoSignal"]            = "SIN SEÑAL",
            ["PressStart"]          = "Pulse START para comenzar",
            ["OutputLog"]           = "REGISTRO DE SALIDA",
            ["VideoCaptureDevice"]  = "Dispositivo de captura de vídeo",
            ["VideoInputConfig"]    = "Configuración entrada de vídeo",
            ["FrameResolution"]     = "Resolución del frame",
            ["AdvancedConfig"]      = "Avanzado (clave=valor)",
            ["DetectDevices"]       = "Detectar",
            ["ScreenCaptureInfo"]   = "Captura de pantalla activa — recorte central enviado a inferencia.",
            ["MacrosTitan"]         = "Macros Titan (CoD)",
            ["StickOverride"]       = "Override del stick",
            ["MacroAdjustments"]    = "Ajustes de macro",
            ["PlayerBlendLbl"]      = "Mezcla jugador (IA activa)",
            ["DisableAiThreshold"]  = "Umbral desact. IA (%)",
            ["ArVertical"]          = "Anti-Retroceso Vertical",
            ["ArHorizontal"]        = "Anti-Retroceso Horizontal",
            ["RapidFireSpeed"]      = "Velocidad Rapid Fire (ms)",
            ["QuickscopeDelay"]     = "Retardo Quickscope (ms)",
            ["JumpShotDelay"]       = "Retardo Jump Shot (ms)",
            ["BunnyHopDelay"]       = "Retardo Bunny Hop (ms)",
            ["StrafePower"]         = "Potencia Strafe",
            ["UserPanel"]           = "PANEL DE USUARIO",
            ["AccountInfo"]         = "Información de la Cuenta",
            ["AccUsername"]         = "Usuario",
            ["AccSubscription"]     = "Suscripción",
            ["AccExpiry"]           = "Expiración",
            ["AccCreated"]          = "Creado",
            ["AccLastLogin"]        = "Último Inicio",
            ["ConfigProfiles"]      = "Perfiles de Configuración",
            ["ActiveProfileLbl"]    = "Perfil Activo:",
            ["NoProfilesMsg"]       = "No se encontraron perfiles — cree uno nuevo para comenzar.",
            ["NewProfilePlaceholder"] = "Nombre del nuevo perfil",
            ["BtnCreate"]           = "CREAR",
            ["BtnLoad"]             = "CARGAR",
            ["BtnSave"]             = "GUARDAR",
            ["BtnCopy"]             = "COPIAR",
            ["BtnPaste"]            = "PEGAR",
            ["BtnDelete"]           = "ELIMINAR",
            ["FuzerMode"]           = "Modo Fuzer",
            ["FuzerExit"]           = "Salir de Fuzer",
        };

        private readonly Dictionary<string, string> _it = new()
        {
            ["Hardware"]    = "HARDWARE",
            ["DetMode"]     = "MODO RILEVAMENTO",
            ["TrackCtrl"]   = "CONTROLLO TRACKING",
            ["Trigger"]     = "GRILLETTO",
            ["Offset"]      = "OFFSET BERSAGLIO",
            ["Recoil"]      = "ANTI-RINCULO",
            ["PixelBot"]    = "PIXELBOT (COLORE)",
            ["Overlay"]     = "OVERLAY",
            ["Vision"]      = "VISIONE & IA",
            ["Save"]        = "SALVA IMMAGINI",
            ["Capture"]     = "CATTURA",
            ["Monitor"]     = "MONITOR",

            ["Protocol"]        = "Protocollo",
            ["Slot"]            = "Slot",
            ["IpAddress"]       = "Indirizzo IP",
            ["Port"]            = "Porta",
            ["UUID"]            = "UUID",
            ["GpuInference"]    = "GPU per Inferenza",
            ["Gpu0"]            = "GPU 0 (principale)",
            ["Gpu1"]            = "GPU 1",
            ["Gpu2"]            = "GPU 2",
            ["PanelKey"]        = "Tasto Pannello (+ Ctrl)",

            ["DM0"]     = "0 — Solo YOLO",
            ["DM1"]     = "1 — YOLO + PB fallback",
            ["DM2"]     = "2 — Solo PixelBot",
            ["DM3"]     = "3 — PB come gate",

            ["SectYolo"]    = "— YOLO —",
            ["SectPB"]      = "— PixelBot —",
            ["Speed"]       = "Velocità",
            ["Smoothness"]  = "Morbidezza",
            ["DeadZone"]    = "Zona morta (px)",
            ["SpeedPB100"]  = "Velocità PB (1–100)",
            ["SmoothPB99"]  = "Morbidezza PB (1–99)",
            ["DeadZonePB"]  = "Zona morta PB (px)",
            ["SpeedHIP"]    = "Velocità HIP",
            ["SpeedADS"]    = "Velocità ADS",
            ["Boost"]       = "Moltiplicatore",
            ["MinForce"]    = "Forza min.",
            ["Damping"]     = "Smorzamento",
            ["ResponseCurve"] = "Curva di risposta",
            ["Curve0"]      = "0 — Lineare",
            ["Curve1"]      = "1 — Quadratico",
            ["Curve2"]      = "2 — Radice quadrata",
            ["Curve3"]      = "3 — Morbida / S-Curve",
            ["Curve4"]      = "4 — Esponenziale",
            ["Curve5"]      = "5 — Bang + Lineare",
            ["Curve6"]      = "6 — Cubica",
            ["TrackFov"]    = "FOV di tracking",
            ["AutoTune"]    = "Auto-Tune",

            ["TriggerLabel"]    = "Grilletto",
            ["InferenceMode"]   = "Modo inferenza",
            ["IM0"]     = "Auto (inferenza sul grilletto)",
            ["IM1"]     = "Costante (tracking sul grilletto)",
            ["IM2"]     = "Costante (sempre attivo)",
            ["IM3"]     = "Spento",

            ["BodyOffset"]  = "Offset corpo  (0=piedi  100=testa)",
            ["IconOffset"]  = "Offset icona  (0=piedi  100=basso)",

            ["SectKmBox"]       = "— KMBox —",
            ["SectTitanTwo"]    = "— Titan Two —",
            ["EnableRecoil"]    = "Attiva Anti-Rinculo",
            ["RecoilVert"]      = "Verticale (px/impulso)",
            ["RecoilHoriz"]     = "Orizzontale (px/impulso)",
            ["Interval"]        = "Intervallo (ms)",
            ["RecoilVertTT2"]   = "Verticale (% stick continuo)",
            ["RecoilHorizTT2"]  = "Orizzontale (% stick continuo)",

            ["ResetDefaults"]       = "↺  Ripristina valori",
            ["TargetColor"]         = "Colore bersaglio",
            ["MinArea"]             = "Area min. (px²)",
            ["MaxArea"]             = "Area max. (px²)",
            ["MinAspect"]           = "Rapporto aspetto min.",
            ["MinSolidity"]         = "Solidità min. (0=off)",
            ["MinCircularity"]      = "Circolarità min. (0=off)",
            ["SatMin"]              = "Saturazione HSV min.",
            ["ValMin"]              = "Luminosità HSV min.",
            ["PersistRadius"]       = "Raggio persistenza (px)",
            ["PersistFrames"]       = "Frame persistenza",
            ["PbVertOffset"]        = "Offset verticale PB  (0=piedi  100=testa)",

            ["Metrics"]         = "METRICHE",
            ["ShowMetrics"]     = "Mostra barra metriche",
            ["DragMetrics"]     = "Trascina la barra per riposizionare",
            ["FovSection"]      = "FOV",
            ["ShowFov"]         = "Mostra FOV",
            ["FovSize"]         = "Dimensione FOV (px)",
            ["FovThickness"]    = "Spessore FOV",
            ["FovStyle"]        = "Stile FOV",
            ["FovColor"]        = "Colore FOV",
            ["Circle"]          = "Cerchio",
            ["Square"]          = "Quadrato",
            ["BoxSection"]      = "RIQUADRI",
            ["ShowBox"]         = "Mostra riquadri",
            ["BoxStyle"]        = "Stile riquadro",
            ["BoxThickness"]    = "Spessore",
            ["BoxFill"]         = "Riempimento",
            ["BoxAlpha"]        = "Opacità fill",
            ["BoxStyleFull"]    = "Quadrato",
            ["BoxStyleCorners"] = "Solo angoli",
            ["BoxStyleRound"]   = "Arrotondato",

            ["Model"]           = "Modello",
            ["Confidence"]      = "Confidenza min.",
            ["ColorFilter"]     = "Filtro colore",
            ["ColorTolerance"]  = "Tolleranza colore",
            ["PreviewLbl"]      = "Anteprima",
            ["PreviewFpsLbl"]   = "FPS Anteprima",

            ["AutoSaveLbl"]     = "Auto-Save",
            ["SaveEnemyOnly"]   = "Solo nemici",
            ["CropSize"]        = "Dimensione crop",

            ["Language"]        = "Lingua",

            ["NoSignal"]            = "NESSUN SEGNALE",
            ["PressStart"]          = "Premi START per iniziare",
            ["OutputLog"]           = "REGISTRO OUTPUT",
            ["VideoCaptureDevice"]  = "Dispositivo di cattura video",
            ["VideoInputConfig"]    = "Configurazione ingresso video",
            ["FrameResolution"]     = "Risoluzione frame",
            ["AdvancedConfig"]      = "Avanzato (chiave=valore)",
            ["DetectDevices"]       = "Rileva",
            ["ScreenCaptureInfo"]   = "Cattura schermo attiva — ritaglio centrale inviato all'inferenza.",
            ["MacrosTitan"]         = "Macros Titan (CoD)",
            ["StickOverride"]       = "Override dello stick",
            ["MacroAdjustments"]    = "Regolazioni macro",
            ["PlayerBlendLbl"]      = "Blend giocatore (IA attiva)",
            ["DisableAiThreshold"]  = "Soglia disatt. IA (%)",
            ["ArVertical"]          = "Anti-Rinculo Verticale",
            ["ArHorizontal"]        = "Anti-Rinculo Orizzontale",
            ["RapidFireSpeed"]      = "Velocità Rapid Fire (ms)",
            ["QuickscopeDelay"]     = "Ritardo Quickscope (ms)",
            ["JumpShotDelay"]       = "Ritardo Jump Shot (ms)",
            ["BunnyHopDelay"]       = "Ritardo Bunny Hop (ms)",
            ["StrafePower"]         = "Potenza Strafe",
            ["UserPanel"]           = "PANNELLO UTENTE",
            ["AccountInfo"]         = "Informazioni Account",
            ["AccUsername"]         = "Utente",
            ["AccSubscription"]     = "Abbonamento",
            ["AccExpiry"]           = "Scadenza",
            ["AccCreated"]          = "Creato il",
            ["AccLastLogin"]        = "Ultimo Accesso",
            ["ConfigProfiles"]      = "Profili di Configurazione",
            ["ActiveProfileLbl"]    = "Profilo Attivo:",
            ["NoProfilesMsg"]       = "Nessun profilo trovato — creane uno per iniziare.",
            ["NewProfilePlaceholder"] = "Nome del nuovo profilo",
            ["BtnCreate"]           = "CREA",
            ["BtnLoad"]             = "CARICA",
            ["BtnSave"]             = "SALVA",
            ["BtnCopy"]             = "COPIA",
            ["BtnPaste"]            = "INCOLLA",
            ["BtnDelete"]           = "ELIMINA",
            ["FuzerMode"]           = "Modalità Fuzer",
            ["FuzerExit"]           = "Esci da Fuzer",
        };

        private readonly Dictionary<string, string> _zh = new()
        {
            ["Hardware"]    = "硬件",
            ["DetMode"]     = "检测模式",
            ["TrackCtrl"]   = "跟踪控制",
            ["Trigger"]     = "触发器",
            ["Offset"]      = "目标偏移",
            ["Recoil"]      = "防后坐力",
            ["PixelBot"]    = "像素机器人(颜色)",
            ["Overlay"]     = "叠加层",
            ["Vision"]      = "视觉与AI",
            ["Save"]        = "保存图像",
            ["Capture"]     = "捕获",
            ["Monitor"]     = "监控",

            ["Protocol"]        = "协议",
            ["Slot"]            = "槽位",
            ["IpAddress"]       = "IP地址",
            ["Port"]            = "端口",
            ["UUID"]            = "UUID",
            ["GpuInference"]    = "推理GPU",
            ["Gpu0"]            = "GPU 0 (主要)",
            ["Gpu1"]            = "GPU 1",
            ["Gpu2"]            = "GPU 2",
            ["PanelKey"]        = "面板快捷键 (+ Ctrl)",

            ["DM0"]     = "0 — 仅YOLO",
            ["DM1"]     = "1 — YOLO + PB备用",
            ["DM2"]     = "2 — 仅PixelBot",
            ["DM3"]     = "3 — PB作为门控",

            ["SectYolo"]    = "— YOLO —",
            ["SectPB"]      = "— PixelBot —",
            ["Speed"]       = "速度",
            ["Smoothness"]  = "平滑度",
            ["DeadZone"]    = "死区 (px)",
            ["SpeedPB100"]  = "PB速度 (1–100)",
            ["SmoothPB99"]  = "PB平滑 (1–99)",
            ["DeadZonePB"]  = "PB死区 (px)",
            ["SpeedHIP"]    = "HIP速度",
            ["SpeedADS"]    = "ADS速度",
            ["Boost"]       = "增益",
            ["MinForce"]    = "最小力度",
            ["Damping"]     = "阻尼",
            ["ResponseCurve"] = "响应曲线",
            ["Curve0"]      = "0 — 线性",
            ["Curve1"]      = "1 — 二次",
            ["Curve2"]      = "2 — 平方根",
            ["Curve3"]      = "3 — 平滑/S曲线",
            ["Curve4"]      = "4 — 指数",
            ["Curve5"]      = "5 — 冲击+线性",
            ["Curve6"]      = "6 — 三次",
            ["TrackFov"]    = "跟踪FOV",
            ["AutoTune"]    = "自动调节",

            ["TriggerLabel"]    = "触发器",
            ["InferenceMode"]   = "推理模式",
            ["IM0"]     = "自动 (仅触发时推理)",
            ["IM1"]     = "持续 (触发时跟踪)",
            ["IM2"]     = "持续 (始终跟踪)",
            ["IM3"]     = "关闭",

            ["BodyOffset"]  = "身体偏移  (0=脚  100=头)",
            ["IconOffset"]  = "图标偏移  (0=脚  100=下方)",

            ["SectKmBox"]       = "— KMBox —",
            ["SectTitanTwo"]    = "— Titan Two —",
            ["EnableRecoil"]    = "启用防后坐力",
            ["RecoilVert"]      = "垂直 (px/脉冲)",
            ["RecoilHoriz"]     = "水平 (px/脉冲)",
            ["Interval"]        = "间隔 (ms)",
            ["RecoilVertTT2"]   = "垂直 (% 连续摇杆)",
            ["RecoilHorizTT2"]  = "水平 (% 连续摇杆)",

            ["ResetDefaults"]       = "↺  重置为默认值",
            ["TargetColor"]         = "目标颜色",
            ["MinArea"]             = "最小面积 (px²)",
            ["MaxArea"]             = "最大面积 (px²)",
            ["MinAspect"]           = "最小宽高比",
            ["MinSolidity"]         = "最小实心度 (0=off)",
            ["MinCircularity"]      = "最小圆度 (0=off)",
            ["SatMin"]              = "HSV最小饱和度",
            ["ValMin"]              = "HSV最小亮度",
            ["PersistRadius"]       = "持续半径 (px)",
            ["PersistFrames"]       = "持续帧数",
            ["PbVertOffset"]        = "PB垂直偏移  (0=脚  100=头)",

            ["Metrics"]         = "指标",
            ["ShowMetrics"]     = "显示指标栏",
            ["DragMetrics"]     = "拖动栏以重新定位",
            ["FovSection"]      = "FOV",
            ["ShowFov"]         = "显示FOV",
            ["FovSize"]         = "FOV大小 (px)",
            ["FovThickness"]    = "FOV粗细",
            ["FovStyle"]        = "FOV样式",
            ["FovColor"]        = "FOV颜色",
            ["Circle"]          = "圆形",
            ["Square"]          = "方形",
            ["BoxSection"]      = "边界框",
            ["ShowBox"]         = "显示框",
            ["BoxStyle"]        = "框样式",
            ["BoxThickness"]    = "粗细",
            ["BoxFill"]         = "填充",
            ["BoxAlpha"]        = "填充透明度",
            ["BoxStyleFull"]    = "方形",
            ["BoxStyleCorners"] = "仅角落",
            ["BoxStyleRound"]   = "圆角",

            ["Model"]           = "模型",
            ["Confidence"]      = "最低置信度",
            ["ColorFilter"]     = "颜色过滤",
            ["ColorTolerance"]  = "颜色容差",
            ["PreviewLbl"]      = "预览",
            ["PreviewFpsLbl"]   = "预览FPS",

            ["AutoSaveLbl"]     = "自动保存",
            ["SaveEnemyOnly"]   = "仅保存敌人",
            ["CropSize"]        = "裁剪大小",

            ["Language"]        = "语言",

            ["NoSignal"]            = "无信号",
            ["PressStart"]          = "按 START 开始",
            ["OutputLog"]           = "输出日志",
            ["VideoCaptureDevice"]  = "视频采集设备",
            ["VideoInputConfig"]    = "视频输入配置",
            ["FrameResolution"]     = "帧分辨率",
            ["AdvancedConfig"]      = "高级 (键=值)",
            ["DetectDevices"]       = "检测",
            ["ScreenCaptureInfo"]   = "全屏捕获已激活 — 中心裁剪发送到推理。",
            ["MacrosTitan"]         = "Macros Titan (CoD)",
            ["StickOverride"]       = "摇杆覆盖",
            ["MacroAdjustments"]    = "宏调整",
            ["PlayerBlendLbl"]      = "玩家混合 (AI活跃)",
            ["DisableAiThreshold"]  = "禁用AI阈值 (%)",
            ["ArVertical"]          = "垂直防后坐力",
            ["ArHorizontal"]        = "水平防后坐力",
            ["RapidFireSpeed"]      = "连射速度 (ms)",
            ["QuickscopeDelay"]     = "快瞄延迟 (ms)",
            ["JumpShotDelay"]       = "跳射延迟 (ms)",
            ["BunnyHopDelay"]       = "兔子跳延迟 (ms)",
            ["StrafePower"]         = "横移力度",
            ["UserPanel"]           = "用户面板",
            ["AccountInfo"]         = "账户信息",
            ["AccUsername"]         = "用户名",
            ["AccSubscription"]     = "订阅",
            ["AccExpiry"]           = "到期",
            ["AccCreated"]          = "创建时间",
            ["AccLastLogin"]        = "上次登录",
            ["ConfigProfiles"]      = "配置方案",
            ["ActiveProfileLbl"]    = "当前方案：",
            ["NoProfilesMsg"]       = "未找到配置方案 — 创建一个新的方案开始使用。",
            ["NewProfilePlaceholder"] = "新方案名称",
            ["BtnCreate"]           = "创建",
            ["BtnLoad"]             = "加载",
            ["BtnSave"]             = "保存",
            ["BtnCopy"]             = "复制",
            ["BtnPaste"]            = "粘贴",
            ["BtnDelete"]           = "删除",
            ["FuzerMode"]           = "Fuzer 模式",
            ["FuzerExit"]           = "退出 Fuzer",
        };

        private Dictionary<string, string> _current;

        private LocalizationManager()
        {
            _current = _pt;
        }

        public string this[string key]
            => _current.TryGetValue(key, out var v) ? v : key;

        public void SetLanguage(string lang)
        {
            _current = lang switch
            {
                "en" => _en,
                "fr" => _fr,
                "es" => _es,
                "it" => _it,
                "zh" => _zh,
                _    => _pt,
            };
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs("Item[]"));
        }
    }
}
